/* automatically generated by rust-bindgen 0.70.1 */

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
pub const UCC_VERSION_MAJOR_SHIFT: u32 = 24;
pub const UCC_VERSION_MINOR_SHIFT: u32 = 16;
pub const UCC_API_MAJOR: u32 = 1;
pub const UCC_API_MINOR: u32 = 9;
pub const UCC_VERSION_STRING: &[u8; 6] = b"1.9.0\0";
pub const UCC_GIT_REVISION: &[u8; 9] = b"281a0eb5\0";
pub const UCC_DT_PREDEFINED_LAST: u32 = 18;
pub const ucc_status_t_UCC_OK: ucc_status_t = 0;
#[doc = "< Operation is posted and is in progress"]
pub const ucc_status_t_UCC_INPROGRESS: ucc_status_t = 1;
#[doc = "< Operation initialized but not posted"]
pub const ucc_status_t_UCC_OPERATION_INITIALIZED: ucc_status_t = 2;
pub const ucc_status_t_UCC_ERR_NOT_SUPPORTED: ucc_status_t = -1;
pub const ucc_status_t_UCC_ERR_NOT_IMPLEMENTED: ucc_status_t = -2;
pub const ucc_status_t_UCC_ERR_INVALID_PARAM: ucc_status_t = -3;
pub const ucc_status_t_UCC_ERR_NO_MEMORY: ucc_status_t = -4;
pub const ucc_status_t_UCC_ERR_NO_RESOURCE: ucc_status_t = -5;
#[doc = "< General purpose return code without specific error"]
pub const ucc_status_t_UCC_ERR_NO_MESSAGE: ucc_status_t = -6;
pub const ucc_status_t_UCC_ERR_NOT_FOUND: ucc_status_t = -7;
pub const ucc_status_t_UCC_ERR_TIMED_OUT: ucc_status_t = -8;
pub const ucc_status_t_UCC_ERR_IO_ERROR: ucc_status_t = -9;
pub const ucc_status_t_UCC_ERR_LAST: ucc_status_t = -100;
#[doc = " @ingroup UCC_UTILS\n @brief Status codes for the UCC operations"]
pub type ucc_status_t = ::std::os::raw::c_int;
extern "C" {
    #[doc = " @ingroup UCC_UTILS\n @brief Routine to convert status code to string"]
    pub fn ucc_status_string(status: ucc_status_t) -> *const ::std::os::raw::c_char;
}
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_lib_info {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_LIB_INIT_DT\n @brief UCC library handle\n\n The ucc library handle is an opaque handle created by the library. It\n abstracts the collective library. It holds the global information and\n resources associated  with the library. The library handle cannot be passed\n from one library instance to another."]
pub type ucc_lib_h = *mut ucc_lib_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_context {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_CONTEXT_DT\n @brief UCC context\n\n The UCC context is an opaque handle to abstract the network resources for\n collective operations. The network resources could be either software or\n hardware. Based on the type of the context, the resources can be shared or\n either be exclusively used. The UCC context is required but not sufficient to\n execute a collective operation."]
pub type ucc_context_h = *mut ucc_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_team {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_TEAM_DT\n @brief UCC team handle\n\n The UCC team handle is an opaque handle created by the library. It abstracts\n the group resources required for the collective operations and participants\n of the collective operation. The participants of the collective operation can\n be an OS process or thread."]
pub type ucc_team_h = *mut ucc_team;
#[doc = " @ingroup UCC_COLLECTIVES_DT\n @brief UCC collective request handle\n\n The UCC request handle is an opaque handle created by the library during the\n invocation of the collective operation. The request may be used to learn the\n status of the collective operation, progress, or complete the collective\n operation."]
pub type ucc_coll_req_h = *mut ucc_coll_req;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_coll_req {
    pub status: ucc_status_t,
}
pub type ucc_coll_req_t = ucc_coll_req;
#[doc = " @ingroup UCC_COLLECTIVES_DT\n @brief UCC collective completion callback\n\n The callback is invoked whenever the collective operation is completed.\n It is not allowed to call UCC APIs from the completion callback except\n for @ref ucc_collective_finalize."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_coll_callback {
    pub cb: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, status: ucc_status_t),
    >,
    pub data: *mut ::std::os::raw::c_void,
}
#[doc = " @ingroup UCC_COLLECTIVES_DT\n @brief UCC collective completion callback\n\n The callback is invoked whenever the collective operation is completed.\n It is not allowed to call UCC APIs from the completion callback except\n for @ref ucc_collective_finalize."]
pub type ucc_coll_callback_t = ucc_coll_callback;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_mem_handle {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_COLLECTIVES\n @brief UCC memory handle\n\n The UCC memory handle is an opaque handle created by the library representing\n the buffer and address."]
pub type ucc_mem_h = *mut ucc_mem_handle;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_lib_config {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_LIB_INIT_DT\n\n @brief UCC library configuration handle"]
pub type ucc_lib_config_h = *mut ucc_lib_config;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_context_config {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_CONTEXT_DT\n\n @brief UCC context configuration handle"]
pub type ucc_context_config_h = *mut ucc_context_config;
#[doc = " @ingroup UCC_COLLECTIVES_DT\n @brief Count datatype to support both small (32 bit) and large counts (64 bit)"]
pub type ucc_count_t = u64;
#[doc = " @ingroup UCC_COLLECTIVES_DT\n @brief Datatype to support both small (32 bit) and large address offsets (64 bit)"]
pub type ucc_aint_t = u64;
pub const ucc_config_print_flags_t_UCC_CONFIG_PRINT_CONFIG: ucc_config_print_flags_t = 1;
pub const ucc_config_print_flags_t_UCC_CONFIG_PRINT_HEADER: ucc_config_print_flags_t = 2;
pub const ucc_config_print_flags_t_UCC_CONFIG_PRINT_DOC: ucc_config_print_flags_t = 4;
pub const ucc_config_print_flags_t_UCC_CONFIG_PRINT_HIDDEN: ucc_config_print_flags_t = 8;
#[doc = " @ingroup UCC_UTILS\n @brief Print configurations"]
pub type ucc_config_print_flags_t = ::std::os::raw::c_uint;
#[doc = " @ingroup UCC_COLLECTIVES_DT\n @brief Datatype for collective tags"]
pub type ucc_coll_id_t = u16;
#[doc = " @ingroup UCC_TEAM_DT"]
pub type ucc_p2p_conn_t = *mut ::std::os::raw::c_void;
#[doc = " @ingroup UCC_TEAM_DT"]
pub type ucc_context_addr_h = *mut ::std::os::raw::c_void;
#[doc = " @ingroup UCC_TEAM_DT"]
pub type ucc_context_addr_len_t = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_ee {
    _unused: [u8; 0],
}
#[doc = " @ingroup UCC_EVENT_DT\n @brief UCC execution engine handle\n\n The UCC execution engine handle is an opaque handle created by the library representing\n the execution context and related queues."]
pub type ucc_ee_h = *mut ucc_ee;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_dt_generic {
    _unused: [u8; 0],
}
pub type ucc_dt_generic_t = ucc_dt_generic;
pub const ucc_dt_type_t_UCC_DATATYPE_PREDEFINED: ucc_dt_type_t = 0;
pub const ucc_dt_type_t_UCC_DATATYPE_GENERIC: ucc_dt_type_t = 1;
pub const ucc_dt_type_t_UCC_DATATYPE_SHIFT: ucc_dt_type_t = 3;
pub const ucc_dt_type_t_UCC_DATATYPE_CLASS_MASK: ucc_dt_type_t = 7;
#[doc = " @ingroup UCC_DATATYPE\n @brief Helper enum for generic/predefined datatype representation\n"]
pub type ucc_dt_type_t = ::std::os::raw::c_uint;
pub type __gnuc_va_list = __builtin_va_list;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 3usize]>,
    pub _short_backupbuf: [::std::os::raw::c_char; 1usize],
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub _prevchain: *mut *mut _IO_FILE,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
impl _IO_FILE {
    #[inline]
    pub fn _flags2(&self) -> ::std::os::raw::c_int {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
    }
    #[inline]
    pub fn set__flags2(&mut self, val: ::std::os::raw::c_int) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 24u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(_flags2: ::std::os::raw::c_int) -> __BindgenBitfieldUnit<[u8; 3usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 3usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 24u8, {
            let _flags2: u32 = unsafe { ::std::mem::transmute(_flags2) };
            _flags2 as u64
        });
        __bindgen_bitfield_unit
    }
}
pub type va_list = __gnuc_va_list;
pub const ucc_coll_type_t_UCC_COLL_TYPE_ALLGATHER: ucc_coll_type_t = 1;
pub const ucc_coll_type_t_UCC_COLL_TYPE_ALLGATHERV: ucc_coll_type_t = 2;
pub const ucc_coll_type_t_UCC_COLL_TYPE_ALLREDUCE: ucc_coll_type_t = 4;
pub const ucc_coll_type_t_UCC_COLL_TYPE_ALLTOALL: ucc_coll_type_t = 8;
pub const ucc_coll_type_t_UCC_COLL_TYPE_ALLTOALLV: ucc_coll_type_t = 16;
pub const ucc_coll_type_t_UCC_COLL_TYPE_BARRIER: ucc_coll_type_t = 32;
pub const ucc_coll_type_t_UCC_COLL_TYPE_BCAST: ucc_coll_type_t = 64;
pub const ucc_coll_type_t_UCC_COLL_TYPE_FANIN: ucc_coll_type_t = 128;
pub const ucc_coll_type_t_UCC_COLL_TYPE_FANOUT: ucc_coll_type_t = 256;
pub const ucc_coll_type_t_UCC_COLL_TYPE_GATHER: ucc_coll_type_t = 512;
pub const ucc_coll_type_t_UCC_COLL_TYPE_GATHERV: ucc_coll_type_t = 1024;
pub const ucc_coll_type_t_UCC_COLL_TYPE_REDUCE: ucc_coll_type_t = 2048;
pub const ucc_coll_type_t_UCC_COLL_TYPE_REDUCE_SCATTER: ucc_coll_type_t = 4096;
pub const ucc_coll_type_t_UCC_COLL_TYPE_REDUCE_SCATTERV: ucc_coll_type_t = 8192;
pub const ucc_coll_type_t_UCC_COLL_TYPE_SCATTER: ucc_coll_type_t = 16384;
pub const ucc_coll_type_t_UCC_COLL_TYPE_SCATTERV: ucc_coll_type_t = 32768;
pub const ucc_coll_type_t_UCC_COLL_TYPE_LAST: ucc_coll_type_t = 32769;
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Enumeration representing the collective operations\n\n  @parblock\n\n  Description\n\n  @ref ucc_coll_type_t represents the collective operations supported by the\n  UCC library. The exact set of supported collective operations depends on\n  UCC build flags, runtime configuration and available communication transports.\n\n  @endparblock\n"]
pub type ucc_coll_type_t = ::std::os::raw::c_uint;
#[doc = "< Default system memory"]
pub const ucc_memory_type_UCC_MEMORY_TYPE_HOST: ucc_memory_type = 0;
#[doc = "< NVIDIA CUDA memory"]
pub const ucc_memory_type_UCC_MEMORY_TYPE_CUDA: ucc_memory_type = 1;
#[doc = "< NVIDIA CUDA managed memory"]
pub const ucc_memory_type_UCC_MEMORY_TYPE_CUDA_MANAGED: ucc_memory_type = 2;
#[doc = "< AMD ROCM memory"]
pub const ucc_memory_type_UCC_MEMORY_TYPE_ROCM: ucc_memory_type = 3;
#[doc = "< AMD ROCM managed system memory"]
pub const ucc_memory_type_UCC_MEMORY_TYPE_ROCM_MANAGED: ucc_memory_type = 4;
pub const ucc_memory_type_UCC_MEMORY_TYPE_LAST: ucc_memory_type = 5;
pub const ucc_memory_type_UCC_MEMORY_TYPE_UNKNOWN: ucc_memory_type = 5;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_memory_type = ::std::os::raw::c_uint;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub use self::ucc_memory_type as ucc_memory_type_t;
#[doc = "  @ingroup UCC_DATATYPE\n\n  @brief Enumeration representing the UCC library's datatype\n\n  @parblock\n\n  Description\n\n  @ref ucc_datatype_t represents the datatypes supported by the UCC library’s\n  collective and reduction operations. The predefined operations\n  are signed and unsigned integers of various sizes, float 16, 32, and 64, and\n  user-defined datatypes. User-defined datatypes are created using\n  @ref ucc_dt_create_generic interface and can support user-defined reduction\n  operations. Predefined reduction operations can be used only with\n  predefined datatypes.\n\n  @endparblock\n"]
pub type ucc_datatype_t = u64;
pub const ucc_generic_dt_ops_field_UCC_GENERIC_DT_OPS_FIELD_FLAGS: ucc_generic_dt_ops_field = 1;
#[doc = " @ingroup UCC_DATATYPE"]
pub type ucc_generic_dt_ops_field = ::std::os::raw::c_uint;
#[doc = "< If set, the created datatype\nrepresents a contiguous memory\nregion with the size specified\nin @ref ucc_generic_dt_ops.contig_size\nfield of @ref ucc_generic_dt_ops"]
pub const ucc_generic_dt_ops_flags_t_UCC_GENERIC_DT_OPS_FLAG_CONTIG: ucc_generic_dt_ops_flags_t = 1;
#[doc = "< If set, the created datatype\nhas user-defined reduction\noperation associated with it.\nreduce.cb and reduce.ctx fields\nof @ref ucc_generic_dt_ops must\nbe initialized. Collective operations\nthat involve reduction (allreduce,\nreduce, reduce_scatter/v) can use\nuser-defined data-types only when\nthis flag is set."]
pub const ucc_generic_dt_ops_flags_t_UCC_GENERIC_DT_OPS_FLAG_REDUCE: ucc_generic_dt_ops_flags_t = 2;
#[doc = " @ingroup UCC_DATATYPE\n @brief Flags that can be specified for generic datatype\n"]
pub type ucc_generic_dt_ops_flags_t = ::std::os::raw::c_uint;
#[doc = " @ingroup UCC_DATATYPE\n @brief Descriptor of user-defined reduction callback\n\n This structure is the argument to the reduce.cb callback. It must implement\n the reduction of n_vectors + 1 data vectors each containing \"count\" elements.\n First vector is \"src1\", other n_vectors have start address\n v_j = src2 + count * dt_extent * stride * j.\n The result is stored in dst, so that\n dst[i] = src1[i] + v0[i] + v1[i] + ... +v_nvectors[i],\n for i in [0:count), where \"+\" represents user-defined reduction of 2 elements"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_reduce_cb_params {
    pub mask: u64,
    pub src1: *mut ::std::os::raw::c_void,
    pub src2: *mut ::std::os::raw::c_void,
    pub dst: *mut ::std::os::raw::c_void,
    pub n_vectors: usize,
    pub count: usize,
    pub stride: usize,
    pub dt: *mut ucc_dt_generic_t,
    pub cb_ctx: *mut ::std::os::raw::c_void,
}
#[doc = " @ingroup UCC_DATATYPE\n @brief Descriptor of user-defined reduction callback\n\n This structure is the argument to the reduce.cb callback. It must implement\n the reduction of n_vectors + 1 data vectors each containing \"count\" elements.\n First vector is \"src1\", other n_vectors have start address\n v_j = src2 + count * dt_extent * stride * j.\n The result is stored in dst, so that\n dst[i] = src1[i] + v0[i] + v1[i] + ... +v_nvectors[i],\n for i in [0:count), where \"+\" represents user-defined reduction of 2 elements"]
pub type ucc_reduce_cb_params_t = ucc_reduce_cb_params;
#[doc = " @ingroup UCC_DATATYPE\n @brief UCC generic data type descriptor\n\n This structure provides a generic datatype descriptor that is used to create\n user-defined datatypes."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_generic_dt_ops {
    pub mask: u64,
    pub flags: u64,
    #[doc = "< size of the datatype if @ref UCC_GENERIC_DT_OPS_FLAG_CONTIG is set"]
    pub contig_size: usize,
    #[doc = " @ingroup UCC_DATATYPE\n @brief Start a packing request.\n\n The pointer refers to application defined start-to-pack routine.\n\n @param [in]  context        User-defined context.\n @param [in]  buffer         Buffer to pack.\n @param [in]  count          Number of elements to pack into the buffer.\n\n @return  A custom state that is passed to the subsequent\n          @ref ucc_generic_dt_ops::pack \"pack()\" routine."]
    pub start_pack: ::std::option::Option<
        unsafe extern "C" fn(
            context: *mut ::std::os::raw::c_void,
            buffer: *const ::std::os::raw::c_void,
            count: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    #[doc = " @ingroup UCC_DATATYPE\n @brief Start an unpacking request.\n\n The pointer refers to application defined start-to-unpack routine.\n\n @param [in]  context        User-defined context.\n @param [in]  buffer         Buffer to unpack to.\n @param [in]  count          Number of elements to unpack in the buffer.\n\n @return  A custom state that is passed later to the subsequent\n          @ref ucc_generic_dt_ops::unpack \"unpack()\" routine."]
    pub start_unpack: ::std::option::Option<
        unsafe extern "C" fn(
            context: *mut ::std::os::raw::c_void,
            buffer: *mut ::std::os::raw::c_void,
            count: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    #[doc = " @ingroup UCC_DATATYPE\n @brief Get the total size of packed data.\n\n The pointer refers to user defined routine that returns the size of data\n in a packed format.\n\n @param [in]  state          State as returned by\n                             @ref ucc_generic_dt_ops::start_pack\n                             \"start_pack()\" routine.\n\n @return  The size of the data in a packed form."]
    pub packed_size:
        ::std::option::Option<unsafe extern "C" fn(state: *mut ::std::os::raw::c_void) -> usize>,
    #[doc = " @ingroup UCC_DATATYPE\n @brief Pack data.\n\n The pointer refers to application defined pack routine.\n\n @param [in]  state          State as returned by\n                             @ref ucc_generic_dt_ops::start_pack\n                             \"start_pack()\" routine.\n @param [in]  offset         Virtual offset in the output stream.\n @param [in]  dest           Destination buffer to pack the data.\n @param [in]  max_length     Maximum length to pack.\n\n @return The size of the data that was written to the destination buffer.\n         Must be less than or equal to @e max_length."]
    pub pack: ::std::option::Option<
        unsafe extern "C" fn(
            state: *mut ::std::os::raw::c_void,
            offset: usize,
            dest: *mut ::std::os::raw::c_void,
            max_length: usize,
        ) -> usize,
    >,
    #[doc = " @ingroup UCC_DATATYPE\n @brief Unpack data.\n\n The pointer refers to application defined unpack routine.\n\n @param [in]  state          State as returned by\n                             @ref ucc_generic_dt_ops::start_unpack\n                             \"start_unpack()\" routine.\n @param [in]  offset         Virtual offset in the input stream.\n @param [in]  src            Source to unpack the data from.\n @param [in]  length         Length to unpack.\n\n @return UCC_OK or an error if unpacking failed."]
    pub unpack: ::std::option::Option<
        unsafe extern "C" fn(
            state: *mut ::std::os::raw::c_void,
            offset: usize,
            src: *const ::std::os::raw::c_void,
            length: usize,
        ) -> ucc_status_t,
    >,
    #[doc = " @ingroup UCC_DATATYPE\n @brief Finish packing/unpacking.\n\n The pointer refers to application defined finish routine.\n\n @param [in]  state          State as returned by\n                             @ref ucc_generic_dt_ops::start_pack\n                             \"start_pack()\"\n                             and\n                             @ref ucc_generic_dt_ops::start_unpack\n                             \"start_unpack()\"\n                             routines."]
    pub finish: ::std::option::Option<unsafe extern "C" fn(state: *mut ::std::os::raw::c_void)>,
    pub reduce: ucc_generic_dt_ops__bindgen_ty_1,
}
#[doc = " @ingroup UCC_DATATYPE\n @brief User-defined reduction callback\n\n The pointer refers to user-defined reduction routine.\n\n @param [in]  params reduction descriptor"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_generic_dt_ops__bindgen_ty_1 {
    pub cb: ::std::option::Option<
        unsafe extern "C" fn(params: *const ucc_reduce_cb_params_t) -> ucc_status_t,
    >,
    pub cb_ctx: *mut ::std::os::raw::c_void,
}
#[doc = " @ingroup UCC_DATATYPE\n @brief UCC generic data type descriptor\n\n This structure provides a generic datatype descriptor that is used to create\n user-defined datatypes."]
pub type ucc_generic_dt_ops_t = ucc_generic_dt_ops;
extern "C" {
    #[doc = " @ingroup UCC_DATATYPE\n @brief Create a generic datatype.\n\n This routine creates a generic datatype object. The generic datatype is\n described by the @a ops @ref ucc_generic_dt_ops_t \"object\" which provides\n a table of routines defining the operations for generic datatype manipulation.\n Typically, generic datatypes are used for integration with datatype engines\n provided with MPI implementations (MPICH, Open MPI, etc). The application\n is responsible for releasing the @a datatype_p  object using\n @ref ucc_dt_destroy \"ucc_dt_destroy()\" routine.\n\n @param [in]  ops          Generic datatype function table as defined by\n                           @ref ucc_generic_dt_ops_t .\n @param [in]  context      Application defined context passed to this\n                           routine.  The context is passed as a parameter\n                           to the routines in the @a ops table.\n @param [out] datatype_p   A pointer to datatype object.\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_dt_create_generic(
        ops: *const ucc_generic_dt_ops_t,
        context: *mut ::std::os::raw::c_void,
        datatype_p: *mut ucc_datatype_t,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_DATATYPE\n @brief Destroy generic datatype"]
    pub fn ucc_dt_destroy(datatype: ucc_datatype_t);
}
pub const ucc_reduction_op_t_UCC_OP_SUM: ucc_reduction_op_t = 0;
pub const ucc_reduction_op_t_UCC_OP_PROD: ucc_reduction_op_t = 1;
pub const ucc_reduction_op_t_UCC_OP_MAX: ucc_reduction_op_t = 2;
pub const ucc_reduction_op_t_UCC_OP_MIN: ucc_reduction_op_t = 3;
pub const ucc_reduction_op_t_UCC_OP_LAND: ucc_reduction_op_t = 4;
pub const ucc_reduction_op_t_UCC_OP_LOR: ucc_reduction_op_t = 5;
pub const ucc_reduction_op_t_UCC_OP_LXOR: ucc_reduction_op_t = 6;
pub const ucc_reduction_op_t_UCC_OP_BAND: ucc_reduction_op_t = 7;
pub const ucc_reduction_op_t_UCC_OP_BOR: ucc_reduction_op_t = 8;
pub const ucc_reduction_op_t_UCC_OP_BXOR: ucc_reduction_op_t = 9;
pub const ucc_reduction_op_t_UCC_OP_MAXLOC: ucc_reduction_op_t = 10;
pub const ucc_reduction_op_t_UCC_OP_MINLOC: ucc_reduction_op_t = 11;
pub const ucc_reduction_op_t_UCC_OP_AVG: ucc_reduction_op_t = 12;
pub const ucc_reduction_op_t_UCC_OP_LAST: ucc_reduction_op_t = 13;
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Enumeration representing the UCC reduction operations\n\n  @parblock\n\n\n  Description\n\n  @ref ucc_reduction_op_t  represents the UCC reduction operations. It is used by the\n  library initialization routine @ref ucc_init to request the operations expected by the user.\n  It is used by the @ref ucc_lib_attr_t to communicate the operations supported by\n  the library.\n\n  @endparblock\n"]
pub type ucc_reduction_op_t = ::std::os::raw::c_uint;
#[doc = "< Single-threaded library model"]
pub const ucc_thread_mode_t_UCC_THREAD_SINGLE: ucc_thread_mode_t = 0;
#[doc = "< Funnel thread model"]
pub const ucc_thread_mode_t_UCC_THREAD_FUNNELED: ucc_thread_mode_t = 1;
#[doc = "< Multithread library model"]
pub const ucc_thread_mode_t_UCC_THREAD_MULTIPLE: ucc_thread_mode_t = 2;
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Enumeration representing the UCC library's thread model\n\n  @parblock\n\n  Description\n\n  @ref ucc_thread_mode_t is used to initialize the UCC library’s thread mode.\n  The UCC library can be configured in three thread modes UCC_THREAD_SINGLE,\n  UCC_THREAD_FUNNELED, and UCC_THREAD_MULTIPLE. In the UCC_THREAD_SINGLE\n  mode, the user program must not be multithreaded. In the UCC_THREAD_FUNNELED\n  mode, the user program may be multithreaded. However, all UCC interfaces\n  should be invoked from the same thread. In the UCC_THREAD_MULTIPLE mode, the\n  user program can be multithreaded and any thread may invoke the UCC\n  operations.\n\n  @endparblock\n"]
pub type ucc_thread_mode_t = ::std::os::raw::c_uint;
#[doc = "< Non-synchronous collectives"]
pub const ucc_coll_sync_type_t_UCC_NO_SYNC_COLLECTIVES: ucc_coll_sync_type_t = 0;
#[doc = "< Synchronous collectives"]
pub const ucc_coll_sync_type_t_UCC_SYNC_COLLECTIVES: ucc_coll_sync_type_t = 1;
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Enumeration representing the collective synchronization model\n\n  @parblock\n\n  Description\n\n  @ref ucc_coll_sync_type_t represents the collective synchronization models.\n  Currently, it supports two synchronization models synchronous and\n  non-synchronous collective models. In the synchronous collective model, the\n  collective communication is not started until participants have not entered\n  the collective operation, and it is not completed until all participants have not\n  completed the collective. In the non-synchronous collective model, collective\n  communication can be started as soon as the participant enters the collective\n  operation and is completed as soon as it completes locally.\n\n  @endparblock\n"]
pub type ucc_coll_sync_type_t = ::std::os::raw::c_uint;
pub const ucc_lib_params_field_UCC_LIB_PARAM_FIELD_THREAD_MODE: ucc_lib_params_field = 1;
pub const ucc_lib_params_field_UCC_LIB_PARAM_FIELD_COLL_TYPES: ucc_lib_params_field = 2;
pub const ucc_lib_params_field_UCC_LIB_PARAM_FIELD_REDUCTION_TYPES: ucc_lib_params_field = 4;
pub const ucc_lib_params_field_UCC_LIB_PARAM_FIELD_SYNC_TYPE: ucc_lib_params_field = 8;
#[doc = "  @ingroup UCC_LIB_INIT_DT"]
pub type ucc_lib_params_field = ::std::os::raw::c_uint;
pub const ucc_lib_attr_field_UCC_LIB_ATTR_FIELD_THREAD_MODE: ucc_lib_attr_field = 1;
pub const ucc_lib_attr_field_UCC_LIB_ATTR_FIELD_COLL_TYPES: ucc_lib_attr_field = 2;
pub const ucc_lib_attr_field_UCC_LIB_ATTR_FIELD_REDUCTION_TYPES: ucc_lib_attr_field = 4;
pub const ucc_lib_attr_field_UCC_LIB_ATTR_FIELD_SYNC_TYPE: ucc_lib_attr_field = 8;
#[doc = "  @ingroup UCC_LIB_INIT_DT"]
pub type ucc_lib_attr_field = ::std::os::raw::c_uint;
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Structure representing the parameters to customize the library\n\n  @parblock\n\n  Description\n\n  @ref ucc_lib_params_t defines the parameters that can be used to customize\n  the library. The bits in \"mask\" bit array is defined by @ref\n  ucc_lib_params_field, which correspond to fields in structure @ref\n  ucc_lib_params_t. The valid fields of the structure is specified by the\n  setting the bit to \"1\" in the bit-array \"mask\". When bits corresponding to\n  the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_lib_params {
    pub mask: u64,
    pub thread_mode: ucc_thread_mode_t,
    pub coll_types: u64,
    pub reduction_types: u64,
    pub sync_type: ucc_coll_sync_type_t,
}
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Structure representing the parameters to customize the library\n\n  @parblock\n\n  Description\n\n  @ref ucc_lib_params_t defines the parameters that can be used to customize\n  the library. The bits in \"mask\" bit array is defined by @ref\n  ucc_lib_params_field, which correspond to fields in structure @ref\n  ucc_lib_params_t. The valid fields of the structure is specified by the\n  setting the bit to \"1\" in the bit-array \"mask\". When bits corresponding to\n  the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
pub type ucc_lib_params_t = ucc_lib_params;
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Structure representing the attributes of the library\n\n  @parblock\n\n  Description\n\n  @ref ucc_lib_attr_t defines the attributes of the library. The bits in\n  \"mask\" bit array is defined by @ref ucc_lib_attr_field, which correspond to\n  fields in structure @ref ucc_lib_attr_t. The valid fields of the structure\n  is specified by the setting the bit to \"1\" in the bit-array \"mask\". When\n  bits corresponding to the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_lib_attr {
    pub mask: u64,
    pub thread_mode: ucc_thread_mode_t,
    pub coll_types: u64,
    pub reduction_types: u64,
    pub sync_type: ucc_coll_sync_type_t,
}
#[doc = "  @ingroup UCC_LIB_INIT_DT\n\n  @brief Structure representing the attributes of the library\n\n  @parblock\n\n  Description\n\n  @ref ucc_lib_attr_t defines the attributes of the library. The bits in\n  \"mask\" bit array is defined by @ref ucc_lib_attr_field, which correspond to\n  fields in structure @ref ucc_lib_attr_t. The valid fields of the structure\n  is specified by the setting the bit to \"1\" in the bit-array \"mask\". When\n  bits corresponding to the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
pub type ucc_lib_attr_t = ucc_lib_attr;
extern "C" {
    #[doc = "  @ingroup UCC_LIB\n\n  @brief The @ref ucc_lib_config_read routine provides a method to read library\n  configuration from the environment and create configuration descriptor.\n\n  @param [out] env_prefix    If not NULL, the routine searches for the\n                             environment variables with the prefix UCC_<env_prefix>. Otherwise, the\n                             routines search for the environment variables that start with the prefix @\n                             UCC_.\n  @param [in]  filename      If not NULL, read configuration values from the\n                             file defined by @e filename. If the file does not exist, it will be ignored\n                             and no error will be reported to the user.\n  @param [out] config        Pointer to configuration descriptor as defined by\n                             ucc_lib_config_h.\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_lib_config_read allocates the @ref ucc_lib_config_h handle and\n  fetches the configuration values from the run-time environment. The run-time\n  environment supported are environment variables or a configuration file.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_lib_config_read(
        env_prefix: *const ::std::os::raw::c_char,
        filename: *const ::std::os::raw::c_char,
        config: *mut ucc_lib_config_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_LIB\n\n  @brief The @ref ucc_lib_config_release routine releases the configuration descriptor\n\n  @param [in] config        Pointer to the configuration descriptor to be released.\n                            Configuration descriptor as defined by @ref\n                            ucc_lib_config_h.\n\n  @parblock\n\n  @b Description\n\n  The routine releases the configuration descriptor that was allocated through\n\n  @endparblock\n\n  @ref ucc_lib_config_read \"ucc_lib_config_read()\" routine.\n"]
    pub fn ucc_lib_config_release(config: ucc_lib_config_h);
}
extern "C" {
    #[doc = "  @ingroup UCC_LIB\n\n  @brief The @ref ucc_lib_config_print routine prints the configuration information\n\n  @param [in]  config        ucc_lib_config_h \"Configuration descriptor\"\n                             to print.\n  @param [in]  stream        Output stream to print the configuration to.\n  @param [in]  title         Configuration title to print.\n  @param [in]  print_flags   Flags that control various printing options.\n\n  @parblock\n\n  @b Description\n\n  The routine prints the configuration information that is stored in\n  ucc_lib_config_h \"configuration\" descriptor.\n\n  @endparblock\n"]
    pub fn ucc_lib_config_print(
        config: ucc_lib_config_h,
        stream: *mut FILE,
        title: *const ::std::os::raw::c_char,
        print_flags: ucc_config_print_flags_t,
    );
}
extern "C" {
    #[doc = "  @ingroup UCC_LIB\n\n  @brief The @ref ucc_lib_config_modify routine modifies the runtime configuration as described by the\n  descriptor.\n\n  @param [in] config   Pointer to the configuration descriptor to be modified\n  @param [in] name     Configuration variable to be modified\n  @param [in] value    Configuration value to set\n\n  @parblock\n\n  @b Description\n\n  The @ref ucc_lib_config_modify routine sets the value of identifier \"name\"\n  to \"value\".\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_lib_config_modify(
        config: ucc_lib_config_h,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_LIB\n @brief Get UCC library version.\n\n This routine returns the UCC library version.\n\n @param [out] major_version       Filled with library major version.\n @param [out] minor_version       Filled with library minor version.\n @param [out] release_number      Filled with library release number."]
    pub fn ucc_get_version(
        major_version: *mut ::std::os::raw::c_uint,
        minor_version: *mut ::std::os::raw::c_uint,
        release_number: *mut ::std::os::raw::c_uint,
    );
}
extern "C" {
    #[doc = " @ingroup UCC_LIB\n @brief Get UCC library version as a string.\n\n This routine returns the UCC library version as a string which consists of:\n \"major.minor.release\"."]
    pub fn ucc_get_version_string() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = "  @ingroup UCC_LIB_INTERNAL\n\n  @brief The @ref ucc_init_version is an internal routine that checks\n  compatibility with a particular UCC API version.\n  @ref ucc_init should be used to create the UCC library handle."]
    pub fn ucc_init_version(
        api_major_version: ::std::os::raw::c_uint,
        api_minor_version: ::std::os::raw::c_uint,
        params: *const ucc_lib_params_t,
        config: ucc_lib_config_h,
        lib_p: *mut ucc_lib_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_LIB\n\n  @brief The @ref ucc_finalize routine finalizes the UCC library.\n\n  @param [in] lib_p   Handle to ucc_lib_h\n                      \"UCC library\".\n\n  @parblock\n\n  @b Description\n\n  A local operation to release the resources and\n  cleanup. All participants that invoked @ref ucc_init should call this\n  routine.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_finalize(lib_p: ucc_lib_h) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_LIB\n\n  @brief The @ref ucc_lib_get_attr routine queries the library attributes.\n\n  @param [out]  lib_attr   Library attributes\n  @param [in]   lib_p      Input library object\n\n  @parblock\n\n  @b Description\n\n  A query operation to get the attributes of the library object. The\n  attributes are library configured values and reflect the choices made by the\n  library implementation.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_lib_get_attr(lib_p: ucc_lib_h, lib_attr: *mut ucc_lib_attr_t) -> ucc_status_t;
}
pub const ucc_context_type_t_UCC_CONTEXT_EXCLUSIVE: ucc_context_type_t = 0;
pub const ucc_context_type_t_UCC_CONTEXT_SHARED: ucc_context_type_t = 1;
#[doc = "  @ingroup UCC_CONTEXT_DT"]
pub type ucc_context_type_t = ::std::os::raw::c_uint;
pub const ucc_context_params_field_UCC_CONTEXT_PARAM_FIELD_TYPE: ucc_context_params_field = 1;
pub const ucc_context_params_field_UCC_CONTEXT_PARAM_FIELD_SYNC_TYPE: ucc_context_params_field = 2;
pub const ucc_context_params_field_UCC_CONTEXT_PARAM_FIELD_OOB: ucc_context_params_field = 4;
pub const ucc_context_params_field_UCC_CONTEXT_PARAM_FIELD_ID: ucc_context_params_field = 8;
pub const ucc_context_params_field_UCC_CONTEXT_PARAM_FIELD_MEM_PARAMS: ucc_context_params_field =
    16;
#[doc = "  @ingroup UCC_CONTEXT_DT"]
pub type ucc_context_params_field = ::std::os::raw::c_uint;
pub const ucc_context_attr_field_UCC_CONTEXT_ATTR_FIELD_TYPE: ucc_context_attr_field = 1;
pub const ucc_context_attr_field_UCC_CONTEXT_ATTR_FIELD_SYNC_TYPE: ucc_context_attr_field = 2;
pub const ucc_context_attr_field_UCC_CONTEXT_ATTR_FIELD_CTX_ADDR: ucc_context_attr_field = 4;
pub const ucc_context_attr_field_UCC_CONTEXT_ATTR_FIELD_CTX_ADDR_LEN: ucc_context_attr_field = 8;
pub const ucc_context_attr_field_UCC_CONTEXT_ATTR_FIELD_WORK_BUFFER_SIZE: ucc_context_attr_field =
    16;
#[doc = "  @ingroup UCC_CONTEXT_DT"]
pub type ucc_context_attr_field = ::std::os::raw::c_uint;
#[doc = " @ingroup UCC_CONTEXT_DT\n\n @brief OOB collective operation for creating the context"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_oob_coll {
    pub allgather: ::std::option::Option<
        unsafe extern "C" fn(
            src_buf: *mut ::std::os::raw::c_void,
            recv_buf: *mut ::std::os::raw::c_void,
            size: usize,
            allgather_info: *mut ::std::os::raw::c_void,
            request: *mut *mut ::std::os::raw::c_void,
        ) -> ucc_status_t,
    >,
    pub req_test: ::std::option::Option<
        unsafe extern "C" fn(request: *mut ::std::os::raw::c_void) -> ucc_status_t,
    >,
    pub req_free: ::std::option::Option<
        unsafe extern "C" fn(request: *mut ::std::os::raw::c_void) -> ucc_status_t,
    >,
    pub coll_info: *mut ::std::os::raw::c_void,
    #[doc = "< Number of endpoints participating in the\noob operation (e.g., number of processes\nrepresenting a ucc team)"]
    pub n_oob_eps: u32,
    #[doc = "< Integer value that represents the position\nof the calling processes in the given oob op:\nthe data specified by \"src_buf\" will be placed\nat the offset \"oob_ep*size\" in the \"recv_buf\".\noob_ep must be uniq at every calling process\nand should be in the range [0:n_oob_eps)."]
    pub oob_ep: u32,
}
#[doc = " @ingroup UCC_CONTEXT_DT\n\n @brief OOB collective operation for creating the context"]
pub type ucc_oob_coll_t = ucc_oob_coll;
#[doc = " @ingroup UCC_CONTEXT_DT\n\n @brief OOB collective operation for creating the context"]
pub type ucc_context_oob_coll_t = ucc_oob_coll_t;
#[doc = " @ingroup UCC_CONTEXT_DT\n\n @brief OOB collective operation for creating the context"]
pub type ucc_team_oob_coll_t = ucc_oob_coll_t;
#[doc = "  @ingroup UCC_CONTEXT_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_mem_map {
    #[doc = "< the address of a buffer to be attached to a UCC context"]
    pub address: *mut ::std::os::raw::c_void,
    #[doc = "< the length of the buffer"]
    pub len: usize,
}
#[doc = "  @ingroup UCC_CONTEXT_DT"]
pub type ucc_mem_map_t = ucc_mem_map;
#[doc = " @ingroup UCC_CONTEXT_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_mem_map_params {
    #[doc = "< array of ucc_mem_map elements"]
    pub segments: *mut ucc_mem_map_t,
    #[doc = "< the number of ucc_mem_map elements"]
    pub n_segments: u64,
}
#[doc = " @ingroup UCC_CONTEXT_DT"]
pub type ucc_mem_map_params_t = ucc_mem_map_params;
#[doc = "  @ingroup UCC_CONTEXT_DT\n\n  @brief Structure representing the parameters to customize the context\n\n  @parblock\n\n  Description\n\n  @ref ucc_context_params_t defines the parameters that can be used to\n  customize the context. The \"mask\" bit array fields are defined by @ref\n  ucc_context_params_field. The bits in \"mask\" bit array is defined by @ref\n  ucc_context_params_field, which correspond to fields in structure @ref\n  ucc_context_params_t. The valid fields of the structure is specified by the\n  setting the bit to \"1\" in the bit-array \"mask\". When bits corresponding to\n  the fields is not set, the fields are not defined.\n\n\n  @endparblock\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_context_params {
    pub mask: u64,
    pub type_: ucc_context_type_t,
    pub sync_type: ucc_coll_sync_type_t,
    pub oob: ucc_context_oob_coll_t,
    pub ctx_id: u64,
    pub mem_params: ucc_mem_map_params_t,
}
#[doc = "  @ingroup UCC_CONTEXT_DT\n\n  @brief Structure representing the parameters to customize the context\n\n  @parblock\n\n  Description\n\n  @ref ucc_context_params_t defines the parameters that can be used to\n  customize the context. The \"mask\" bit array fields are defined by @ref\n  ucc_context_params_field. The bits in \"mask\" bit array is defined by @ref\n  ucc_context_params_field, which correspond to fields in structure @ref\n  ucc_context_params_t. The valid fields of the structure is specified by the\n  setting the bit to \"1\" in the bit-array \"mask\". When bits corresponding to\n  the fields is not set, the fields are not defined.\n\n\n  @endparblock\n"]
pub type ucc_context_params_t = ucc_context_params;
#[doc = "  @ingroup UCC_CONTEXT_DT\n\n  @brief Structure representing context attributes\n\n  @parblock\n\n  Description\n\n  @ref ucc_context_attr_t defines the attributes of the context. The bits in\n  \"mask\" bit array is defined by @ref ucc_context_attr_field, which correspond to\n  fields in structure @ref ucc_context_attr_t. The valid fields of the structure\n  is specified by the setting the bit to \"1\" in the bit-array \"mask\". When\n  bits corresponding to the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_context_attr {
    pub mask: u64,
    pub type_: ucc_context_type_t,
    pub sync_type: ucc_coll_sync_type_t,
    pub ctx_addr: ucc_context_addr_h,
    pub ctx_addr_len: ucc_context_addr_len_t,
    pub global_work_buffer_size: u64,
}
#[doc = "  @ingroup UCC_CONTEXT_DT\n\n  @brief Structure representing context attributes\n\n  @parblock\n\n  Description\n\n  @ref ucc_context_attr_t defines the attributes of the context. The bits in\n  \"mask\" bit array is defined by @ref ucc_context_attr_field, which correspond to\n  fields in structure @ref ucc_context_attr_t. The valid fields of the structure\n  is specified by the setting the bit to \"1\" in the bit-array \"mask\". When\n  bits corresponding to the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
pub type ucc_context_attr_t = ucc_context_attr;
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief Routine reads the configuration information for contexts from the\n  runtime enviornment and creates the configuration descriptor.\n\n  @param [in]  lib_handle    Library handle\n  @param [in]  filename      If not NULL, read configuration values from the\n                             file defined by @e filename. If the file does not exist,\n                             it will be ignored and no error will be reported to the user.\n  @param [out] config        Pointer to configuration descriptor as defined by\n                             @ref ucc_context_config_h.\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_context_config_read allocates the @ref ucc_lib_config_h handle and\n  fetches the configuration values from the run-time environment. The run-time\n  environment supported are environment variables or a configuration file. It uses\n  the env_prefix from @ref ucc_lib_config_read. If env_prefix is not NULL, the routine\n  searches for the environment variables with the prefix UCC_<env_prefix>. Otherwise, the\n  routines search for the environment variables that start with the prefix @ UCC_.\n\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_context_config_read(
        lib_handle: ucc_lib_h,
        filename: *const ::std::os::raw::c_char,
        config: *mut ucc_context_config_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The @ref ucc_context_config_release routine releases the configuration descriptor.\n\n  @param [in] config        Pointer to the configuration descriptor to be released.\n                            Configuration descriptor as defined by @ref ucc_context_config_h\n\n  @parblock\n\n  @b Description\n\n  The routine releases the configuration descriptor that was allocated through\n  @ref ucc_context_config_read \"ucc_context_config_read()\" routine.\n\n  @endparblock\n"]
    pub fn ucc_context_config_release(config: ucc_context_config_h);
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The @ref ucc_context_config_print routine prints the configuration information\n\n  @param [in]  config        ucc_context_config_h \"Configuration descriptor\"\n                             to print.\n  @param [in]  stream        Output stream to print the configuration to.\n  @param [in]  title         Configuration title to print.\n  @param [in]  print_flags   Flags that control various printing options.\n\n  @parblock\n\n  @b Description\n\n  The routine prints the configuration information that is stored in\n  ucc_context_config_h \"configuration\" descriptor.\n\n  @endparblock\n"]
    pub fn ucc_context_config_print(
        config: ucc_context_config_h,
        stream: *mut FILE,
        title: *const ::std::os::raw::c_char,
        print_flags: ucc_config_print_flags_t,
    );
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The @ref ucc_context_config_modify routine modifies the runtime configuration\n                  of UCC context (optionally for a given CLS)\n\n  @param [in] config    Pointer to the configuration descriptor to be modified\n  @param [in] component CL/TL component (e.g. \"tl/ucp\" or \"cl/basic\") or NULL.\nIf NULL then core context config is modified.\n  @param [in] name      Configuration variable to be modified\n  @param [in] value     Configuration value to set\n\n  @parblock\n\n  @b Description\n\n  The @ref ucc_context_config_modify routine sets the value of identifier \"name\"\n  to \"value\" for a specified CL.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_context_config_modify(
        config: ucc_context_config_h,
        component: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The @ref ucc_context_create routine creates the context handle.\n\n  @param [in]   lib_handle  Library handle\n  @param [in]   params      Customizations for the communication context\n  @param [in]   config      Configuration for the communication context to read\n                            from environment\n  @param [out]  context     Pointer to the newly created communication context\n\n  @parblock\n\n  @b Description\n\n  The @ref ucc_context_create creates the context and @ref ucc_context_destroy\n  releases the resources and destroys the context state. The creation of\n  context does not necessarily indicate its readiness to be used for\n  collective or other group operations. On success, the context handle will be\n  created and ucc_status_t will return UCC_OK. On error, the context object\n  will not be created and corresponding error code as defined by\n  @ref ucc_status_t is returned.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_context_create(
        lib_handle: ucc_lib_h,
        params: *const ucc_context_params_t,
        config: ucc_context_config_h,
        context: *mut ucc_context_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The @ref ucc_context_progress routine progresses the operations\n  on the context handle.\n\n  @param [in]  context  Communication context handle to be progressed\n\n  @parblock\n\n  @b Description\n\n  The @ref ucc_context_progress routine progresses the operations on the\n  content handle. It does not block for lack of resources or communication.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_context_progress(context: ucc_context_h) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The @ref ucc_context_destroy routine frees the context handle.\n\n  @param [in]  context  Communication context handle to be released\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_context_destroy routine releases the resources associated\n  with the handle @e context. All teams associated with the context should be\n  released before this. It is invalid to associate any team with this handle\n  after the routine is called.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_context_destroy(context: ucc_context_h) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_CONTEXT\n\n  @brief The routine queries the attributes of the context handle.\n\n  @param [in]   context          Communication context\n  @param [out]  context_attr     Attributes of the communication context\n\n  @parblock\n\n  @b Description\n\n  @brief @ref ucc_context_get_attr routine queries the context handle\n  attributes described by @ref ucc_context_attr.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_context_get_attr(
        context: ucc_context_h,
        context_attr: *mut ucc_context_attr_t,
    ) -> ucc_status_t;
}
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_ORDERING: ucc_team_params_field = 1;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_OUTSTANDING_COLLS: ucc_team_params_field = 2;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_EP: ucc_team_params_field = 4;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_EP_LIST: ucc_team_params_field = 8;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_EP_RANGE: ucc_team_params_field = 16;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_TEAM_SIZE: ucc_team_params_field = 32;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_SYNC_TYPE: ucc_team_params_field = 64;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_OOB: ucc_team_params_field = 128;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_P2P_CONN: ucc_team_params_field = 256;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_MEM_PARAMS: ucc_team_params_field = 512;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_EP_MAP: ucc_team_params_field = 1024;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_ID: ucc_team_params_field = 2048;
pub const ucc_team_params_field_UCC_TEAM_PARAM_FIELD_FLAGS: ucc_team_params_field = 4096;
#[doc = "  @ingroup UCC_TEAM_DT"]
pub type ucc_team_params_field = ::std::os::raw::c_uint;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_POST_ORDERING: ucc_team_attr_field = 1;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_OUTSTANDING_CALLS: ucc_team_attr_field = 2;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_EP: ucc_team_attr_field = 4;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_EP_RANGE: ucc_team_attr_field = 8;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_SYNC_TYPE: ucc_team_attr_field = 16;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_MEM_PARAMS: ucc_team_attr_field = 32;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_SIZE: ucc_team_attr_field = 64;
pub const ucc_team_attr_field_UCC_TEAM_ATTR_FIELD_EPS: ucc_team_attr_field = 128;
#[doc = "  @ingroup UCC_TEAM_DT"]
pub type ucc_team_attr_field = ::std::os::raw::c_uint;
pub const ucc_team_flags_UCC_TEAM_FLAG_COLL_WORK_BUFFER: ucc_team_flags = 1;
#[doc = " @ingroup UCC_TEAM_DT"]
pub type ucc_team_flags = ::std::os::raw::c_uint;
#[doc = "  @ingroup UCC_TEAM_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_team_p2p_conn {
    pub conn_info_lookup: ::std::option::Option<
        unsafe extern "C" fn(
            conn_ctx: *mut ::std::os::raw::c_void,
            ep: u64,
            conn_info: *mut *mut ucc_p2p_conn_t,
            request: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub conn_info_release: ::std::option::Option<
        unsafe extern "C" fn(conn_info: *mut ucc_p2p_conn_t) -> ::std::os::raw::c_int,
    >,
    pub conn_ctx: *mut ::std::os::raw::c_void,
    pub req_test: ::std::option::Option<
        unsafe extern "C" fn(request: *mut ::std::os::raw::c_void) -> ucc_status_t,
    >,
    pub req_free: ::std::option::Option<
        unsafe extern "C" fn(request: *mut ::std::os::raw::c_void) -> ucc_status_t,
    >,
}
#[doc = "  @ingroup UCC_TEAM_DT"]
pub type ucc_team_p2p_conn_t = ucc_team_p2p_conn;
#[doc = " When set to this value, the collective participants shall post the operation\n in the same order."]
pub const ucc_post_ordering_t_UCC_COLLECTIVE_POST_ORDERED: ucc_post_ordering_t = 0;
#[doc = " When set to this value, the collective participants shall post the operation\n in any order."]
pub const ucc_post_ordering_t_UCC_COLLECTIVE_POST_UNORDERED: ucc_post_ordering_t = 1;
#[doc = " When set to this value, the collective participants shall initialize the operation\n in the same order."]
pub const ucc_post_ordering_t_UCC_COLLECTIVE_INIT_ORDERED: ucc_post_ordering_t = 2;
#[doc = " When set to this value, the collective participants shall initialize the operation\n in any order."]
pub const ucc_post_ordering_t_UCC_COLLECTIVE_INIT_UNORDERED: ucc_post_ordering_t = 3;
#[doc = " When set to this value, the collective participants shall initialize and\n post the operation in the same order."]
pub const ucc_post_ordering_t_UCC_COLLECTIVE_INIT_AND_POST_ORDERED: ucc_post_ordering_t = 4;
#[doc = " When set to this value, the collective participants shall initialize and\n post the operation in any order."]
pub const ucc_post_ordering_t_UCC_COLLECTIVE_INIT_AND_POST_UNORDERED: ucc_post_ordering_t = 5;
#[doc = "  @ingroup UCC_TEAM_DT"]
pub type ucc_post_ordering_t = ::std::os::raw::c_uint;
pub const ucc_ep_range_type_t_UCC_COLLECTIVE_EP_RANGE_CONTIG: ucc_ep_range_type_t = 0;
pub const ucc_ep_range_type_t_UCC_COLLECTIVE_EP_RANGE_NONCONTIG: ucc_ep_range_type_t = 1;
#[doc = "  @ingroup UCC_TEAM_DT"]
pub type ucc_ep_range_type_t = ::std::os::raw::c_uint;
#[doc = "  @ingroup UCC_TEAM_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_ep_map_strided {
    pub start: u64,
    pub stride: i64,
}
#[doc = "  @ingroup UCC_TEAM_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_ep_map_array {
    pub map: *mut ::std::os::raw::c_void,
    #[doc = "< 4 if array is int, 8 if e.g. uint64_t"]
    pub elem_size: usize,
}
#[doc = "  @ingroup UCC_TEAM_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_ep_map_cb {
    pub cb: ::std::option::Option<
        unsafe extern "C" fn(ep: u64, cb_ctx: *mut ::std::os::raw::c_void) -> u64,
    >,
    pub cb_ctx: *mut ::std::os::raw::c_void,
}
#[doc = "< The ep range of the team spans all eps from a context."]
pub const ucc_ep_map_type_t_UCC_EP_MAP_FULL: ucc_ep_map_type_t = 1;
#[doc = "< The ep range of the team can be described by the 2 values: start, stride."]
pub const ucc_ep_map_type_t_UCC_EP_MAP_STRIDED: ucc_ep_map_type_t = 2;
#[doc = "< The ep range is given as an array of intergers that map the ep in the team to\nthe team_context rank."]
pub const ucc_ep_map_type_t_UCC_EP_MAP_ARRAY: ucc_ep_map_type_t = 3;
#[doc = "< The ep range mapping is defined as callback provided by the UCC user."]
pub const ucc_ep_map_type_t_UCC_EP_MAP_CB: ucc_ep_map_type_t = 4;
#[doc = "  @ingroup UCC_TEAM_DT"]
pub type ucc_ep_map_type_t = ::std::os::raw::c_uint;
#[doc = "  @ingroup UCC_TEAM_DT"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ucc_ep_map_t {
    pub type_: ucc_ep_map_type_t,
    #[doc = "< number of eps mapped to ctx"]
    pub ep_num: u64,
    pub __bindgen_anon_1: ucc_ep_map_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucc_ep_map_t__bindgen_ty_1 {
    pub strided: ucc_ep_map_strided,
    pub array: ucc_ep_map_array,
    pub cb: ucc_ep_map_cb,
}
#[doc = "  @ingroup UCC_TEAM_DT\n\n  @brief Structure representing the parameters to customize the team\n\n  @parblock\n\n  Description\n\n  @ref ucc_team_params_t defines the parameters that can be used to customize\n  the team. The \"mask\" bit array fields are defined by @ref\n  ucc_team_params_field. The bits in \"mask\" bit array is defined by @ref\n  ucc_team_params_field, which correspond to fields in structure @ref\n  ucc_team_params_t. The valid fields of the structure is specified by the\n  setting the bit to \"1\" in the bit-array \"mask\". When bits corresponding to\n  the fields is not set, the fields are not defined.\n\n\n\n  @endparblock\n"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ucc_team_params {
    pub mask: u64,
    pub flags: u64,
    #[doc = " @ref ucc_team_params.ordering is set to one the values defined by @ref\n  ucc_post_ordering_t"]
    pub ordering: ucc_post_ordering_t,
    #[doc = " @ref ucc_team_params.outstanding_colls represents the number of outstanding non-blocking\n calls the user expects to post to the team. If the user posts more non-blocking\n calls than set, the behavior is undefined. If not set, there is no limit on\n the number of outstanding calls to be posted."]
    pub outstanding_colls: u64,
    #[doc = " @ref ucc_team_params.ep The endpoint is a non-negative unique integer identifying the\n participant in the collective. If ep is not set, and @ref ucc_team_params.oob is not set, the\n library generates the ep. The generated ep can be queried using the @ref\n ucc_team_get_attr interface."]
    pub ep: u64,
    #[doc = " @ref ucc_team_params.ep_list The endpoint list provides the list of eps participating to\n  create the team."]
    pub ep_list: *mut u64,
    #[doc = " @ref ucc_team_params.ep_range can be either contiguous or not\n  contiguous. It is a hint to the library."]
    pub ep_range: ucc_ep_range_type_t,
    #[doc = " @ref ucc_team_params.team_size The team size is the number of participants in the team. If\n @ref ucc_team_params.oob is provided, the team size and @ref\n ucc_oob_coll.n_oob_eps should be the same."]
    pub team_size: u64,
    #[doc = " @ref ucc_team_params.sync_type The options for sync_type are provided by @ref\n ucc_coll_sync_type_t"]
    pub sync_type: ucc_coll_sync_type_t,
    #[doc = " @ref ucc_team_params.oob The signature of the function is defined by @ref\n ucc_oob_coll_t\n . The oob is used for exchanging information between the team\n participants during team creation. The user is\n responsible for implementing the oob operation. The relation between @ref\n ucc_team_params.ep and @ref ucc_oob_coll.oob_ep is defined as below:\n\n - When both are not provided. The library is responsible for generating the ep,\n which can be then queried via the @ref ucc_team_get_attr interface. This\n requires, however, ucc_params_t ep_map to be set and context created by\n @ref ucc_oob_coll. The behavior is undefined, when neither @ref\n ucc_team_params.ep or @ref ucc_team_params.ep_map, or @ref\n ucc_team_params.oob is not set.\n\n - When @ref ucc_team_params.ep is provided and @ref ucc_team_params.oob is\n not provided. The “ep” is the unique integer for the participant.\n\n - When @ref ucc_oob_coll.oob_ep is provided and @ref ucc_team_params.ep\n is not provided. The “ep” will be equivalent to @ref ucc_oob_coll.oob_ep.\n\n - When both are provided, the @ref ucc_oob_coll.oob_ep and @ref\n ucc_team_params_t.ep should be same. Otherwise, it\n is undefined."]
    pub oob: ucc_team_oob_coll_t,
    #[doc = " @ref ucc_team_params.p2p_conn is a callback function for the gathering\n the point-to-point communication information."]
    pub p2p_conn: ucc_team_p2p_conn_t,
    #[doc = " @ref ucc_team_params.mem_params provides an ability to attach a buffer\n to the team. This can be used as input/output or control buffer for the\n team. Typically, it can be useful for one-sided collective\n implementation."]
    pub mem_params: ucc_mem_map_params_t,
    #[doc = " @ref ucc_team_params.ep_map provides a mapping between @ref\n ucc_oob_coll.oob_ep used by\n the team and @ref ucc_oob_coll.oob_ep\n used by the context. The mapping options are defined by @ref\n ucc_ep_map_t. The definition is valid only when context is created with\n an @ref ucc_oob_coll."]
    pub ep_map: ucc_ep_map_t,
    #[doc = " @ref ucc_team_params.id\n The team id is a unique integer identifying the team that is active. The\n integer is unique within the process and not the job .i.e., any two active\n non-overlapping teams can have the same id. This semantic helps to avoid a\n global information exchange .i.e, the processes or threads not\n participating in the particular, need not participate in the team\n creation. If not provided, the team id is created internally. For the MPI\n programming model, this can be inherited from the MPI communicator id."]
    pub id: u64,
}
#[doc = "  @ingroup UCC_TEAM_DT\n\n  @brief Structure representing the parameters to customize the team\n\n  @parblock\n\n  Description\n\n  @ref ucc_team_params_t defines the parameters that can be used to customize\n  the team. The \"mask\" bit array fields are defined by @ref\n  ucc_team_params_field. The bits in \"mask\" bit array is defined by @ref\n  ucc_team_params_field, which correspond to fields in structure @ref\n  ucc_team_params_t. The valid fields of the structure is specified by the\n  setting the bit to \"1\" in the bit-array \"mask\". When bits corresponding to\n  the fields is not set, the fields are not defined.\n\n\n\n  @endparblock\n"]
pub type ucc_team_params_t = ucc_team_params;
#[doc = "  @ingroup UCC_TEAM_DT\n\n  @brief Structure representing the team attributes\n\n  @parblock\n\n  Description\n\n  @ref ucc_team_attr_t defines the attributes of the team. The bits in\n  \"mask\" bit array is defined by @ref ucc_team_attr_field, which correspond to\n  fields in structure @ref ucc_team_attr_t. The valid fields of the structure\n  is specified by the setting the bit to \"1\" in the bit-array \"mask\". When\n  bits corresponding to the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_team_attr {
    pub mask: u64,
    pub ordering: ucc_post_ordering_t,
    pub outstanding_colls: u64,
    pub ep: u64,
    pub ep_range: ucc_ep_range_type_t,
    pub sync_type: ucc_coll_sync_type_t,
    pub mem_params: ucc_mem_map_params_t,
    pub size: u32,
    pub eps: *mut u64,
}
#[doc = "  @ingroup UCC_TEAM_DT\n\n  @brief Structure representing the team attributes\n\n  @parblock\n\n  Description\n\n  @ref ucc_team_attr_t defines the attributes of the team. The bits in\n  \"mask\" bit array is defined by @ref ucc_team_attr_field, which correspond to\n  fields in structure @ref ucc_team_attr_t. The valid fields of the structure\n  is specified by the setting the bit to \"1\" in the bit-array \"mask\". When\n  bits corresponding to the fields is not set, the fields are not defined.\n\n  @endparblock\n"]
pub type ucc_team_attr_t = ucc_team_attr;
extern "C" {
    #[doc = "  @ingroup UCC_TEAM\n\n  @brief The routine is a method to create the team.\n\n  @param  [in]  contexts           Communication contexts abstracting the resources\n  @param  [in]  num_contexts       Number of contexts passed for the create operation\n  @param  [in]  team_params        User defined configurations for the team\n  @param  [out] new_team           Team handle\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_team_create_post is a nonblocking collective operation to create\n  the team handle. Overlapping of multiple ucc\\_team\\_create\\_post operations\n  are invalid. The post takes in parameters ucc_context_h and ucc_team_params_t.\n  The ucc_team_params_t provides user configuration to customize the team and,\n  ucc_context_h provides the resources for the team and collectives.\n  The routine returns immediately after posting the operation with the\n  new team handle. However, the team handle is not ready for posting\n  the collective operation. ucc_team_create_test operation is used to learn\n  the status of the new team handle. On error, the team handle will not\n  be created and corresponding error code as defined by @ref ucc_status_t is\n  returned.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_team_create_post(
        contexts: *mut ucc_context_h,
        num_contexts: u32,
        team_params: *const ucc_team_params_t,
        new_team: *mut ucc_team_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_TEAM\n\n  @brief The routine queries the status of the team creation operation.\n\n  @param  [in] team  Team handle to test\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_team_create_test routines tests the status of team handle.\n  If required it can progress the communication but cannot block on the\n  communications. On error, the team handle becomes invalid, user is responsible\n  to call ucc_team_destroy to destroy team and free allocated resources.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_team_create_test(team: ucc_team_h) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_TEAM\n\n  @brief The team frees the team handle.\n\n  @param  [in] team  Destroy previously created team and release all resources\n                     associated with it.\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_team_destroy is a nonblocking collective operation to release all\n  resources associated with the team handle, and destroy the team handle. It is\n  invalid to post a collective operation after the ucc_team_destroy operation.\n  It is invalid to call @ref ucc_team_destroy operation while @ref\n  ucc_team_create_post is in progress. It is the user's responsibility to ensure\n  there is one outstanding @ref ucc_team_create_post or @ref ucc_team_destroy\n  operation is in progress.\n\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t\n"]
    pub fn ucc_team_destroy(team: ucc_team_h) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_TEAM\n\n  @brief The routine returns the attributes of the team.\n\n  @param [in]   team        Team handle\n  @param [out]  team_attr   Attributes of the team\n\n  @parblock\n\n  @b Description\n\n  @brief @ref ucc_team_get_attr routine queries the team handle\n  attributes. The attributes of the team handle are described by the team\n  attributes @ref ucc_team_attr_t\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_team_get_attr(team: ucc_team_h, team_attr: *mut ucc_team_attr_t) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_TEAM\n\n  @brief The routine creates a new team from the parent team.\n\n  @param [in]    my_ep          Endpoint of the process/thread calling the split operation\n  @param [in]    parent_team    Parent team handle from which a new team handle is created\n  @param [in]    included       Variable indicating whether a\n                                process/thread participates in the newly created team;\n                                value 1 indicates the participation and value 0 indicates\n                                otherwise\n  @param [out]   new_team       Pointer to the new team handle\n\n  @parblock\n\n  @b Description\n\n  @brief ucc_team_create_from_parent is a nonblocking collective operation,\n  which creates a new team from the parent team. If a participant intends to\n  participate in the new team, it passes a TRUE value for the \"included\"\n  parameter. Otherwise, it passes FALSE. The routine returns immediately after\n  the post-operation. To learn the completion of the team create operation, the\n  ucc_team_create_test operation is used.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_team_create_from_parent(
        my_ep: u64,
        included: u32,
        parent_team: ucc_team_h,
        new_team: *mut ucc_team_h,
    ) -> ucc_status_t;
}
#[doc = "< If set, the\noutput buffer is\nidentical to the\ninput buffer."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_IN_PLACE: ucc_coll_args_flags_t = 1;
#[doc = "< If set, the\ncollective is\nconsidered\npersistent.\nOnly, the\npersistent\ncollective\ncan be called\nmultiple times with\nthe same request."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_PERSISTENT: ucc_coll_args_flags_t = 2;
#[doc = "< If set, the count\nis 64bit, otherwise,\nit is 32 bit."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_COUNT_64BIT: ucc_coll_args_flags_t = 4;
#[doc = "< If set, the\ndisplacement is\n64bit, otherwise, it\nis 32 bit."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_DISPLACEMENTS_64BIT: ucc_coll_args_flags_t = 8;
#[doc = "< If set, the src\nbuffer is considered\ncontiguous.\nParticularly, useful\nfor alltoallv\noperation."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_CONTIG_SRC_BUFFER: ucc_coll_args_flags_t = 16;
#[doc = "<If set, the dst\nbuffer is considered\ncontiguous.\nParticularly, useful\nfor alltoallv\noperation."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_CONTIG_DST_BUFFER: ucc_coll_args_flags_t = 32;
#[doc = "<If set and the elapsed\ntime after @ref ucc_collective_post\n(or @ref ucc_collective_triggered_post)\nis greater than @ref ucc_coll_args_t.timeout,\nthe library returns UCC_ERR_TIMED_OUT\non the calling thread.\nNote, the status is not guaranteed\nto be global on all the processes\nparticipating in the collective."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_TIMEOUT: ucc_coll_args_flags_t = 64;
#[doc = "< If set, both src\nand dst buffers\nreside in a memory\nmapped region.\nUseful for one-sided\ncollectives."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_MEM_MAPPED_BUFFERS: ucc_coll_args_flags_t = 128;
#[doc = "< If set, indicates\nthe src_memh memory\nhandle is an array of\nglobal handles."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_SRC_MEMH_GLOBAL: ucc_coll_args_flags_t = 256;
#[doc = "< If set, indicates\nthe dst_memh memory\nhandle is an array of\nglobal handles."]
pub const ucc_coll_args_flags_t_UCC_COLL_ARGS_FLAG_DST_MEMH_GLOBAL: ucc_coll_args_flags_t = 512;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_coll_args_flags_t = ::std::os::raw::c_uint;
#[doc = "< When the flag is\nset, the user\nprefers the library\nto choose an\nalgorithm\nimplementation\noptimized for the\nbest overlap of CPU\nresources."]
pub const ucc_coll_args_hints_t_UCC_COLL_ARGS_HINT_OPTIMIZE_OVERLAP_CPU: ucc_coll_args_hints_t =
    16777216;
#[doc = "< When the flag is\nset, the user\nprefers the library\nto choose an\nalgorithm\nimplementation\noptimized for the\nbest overlap of GPU\nresources."]
pub const ucc_coll_args_hints_t_UCC_COLL_ARGS_HINT_OPTIMIZE_OVERLAP_GPU: ucc_coll_args_hints_t =
    33554432;
#[doc = "<  When the flag is\nset, the user prefers\nthe library to choose\nan algorithm\nimplementation\noptimized for the\nlatency."]
pub const ucc_coll_args_hints_t_UCC_COLL_ARGS_HINT_OPTIMIZE_LATENCY: ucc_coll_args_hints_t =
    67108864;
pub const ucc_coll_args_hints_t_UCC_COLL_ARGS_HINT_CONTIG_SRC_BUFFER: ucc_coll_args_hints_t = 16;
pub const ucc_coll_args_hints_t_UCC_COLL_ARGS_HINT_CONTIG_DST_BUFFER: ucc_coll_args_hints_t = 32;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_coll_args_hints_t = ::std::os::raw::c_uint;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_coll_buffer_info_v {
    #[doc = "< Starting address of the send/recv buffer"]
    pub buffer: *mut ::std::os::raw::c_void,
    #[doc = "< Array of counts of type @ref ucc_count_t\ndescribing the total number of elements"]
    pub counts: *mut ucc_count_t,
    #[doc = "< Displacement array of team size and\ntype @ref ucc_aint_t. Entry i specifies\nthe displacement relative to the start\naddress for the incoming data(\noutgoing data) for the team member i. For\nsend buffer the data is fetched from this\ndisplacement and for receive buffer the\nincoming data is placed at this\ndisplacement."]
    pub displacements: *mut ucc_aint_t,
    #[doc = "< Datatype of each buffer element"]
    pub datatype: ucc_datatype_t,
    #[doc = "< Memory type of buffer as defined by @ref\nucc_memory_type"]
    pub mem_type: ucc_memory_type_t,
}
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_coll_buffer_info_v_t = ucc_coll_buffer_info_v;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_coll_buffer_info {
    #[doc = "< Starting address of the send/recv buffer"]
    pub buffer: *mut ::std::os::raw::c_void,
    #[doc = "< Total number of elements in the buffer"]
    pub count: ucc_count_t,
    #[doc = "< Datatype of each buffer element"]
    pub datatype: ucc_datatype_t,
    #[doc = "< Memory type of buffer as defined by @ref\nucc_memory_type"]
    pub mem_type: ucc_memory_type_t,
}
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_coll_buffer_info_t = ucc_coll_buffer_info;
pub const ucc_error_type_t_UCC_ERR_TYPE_LOCAL: ucc_error_type_t = 0;
pub const ucc_error_type_t_UCC_ERR_TYPE_GLOBAL: ucc_error_type_t = 1;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_error_type_t = ::std::os::raw::c_uint;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_FLAGS: ucc_coll_args_field = 1;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_TAG: ucc_coll_args_field = 2;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_CB: ucc_coll_args_field = 4;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_GLOBAL_WORK_BUFFER: ucc_coll_args_field = 8;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_ACTIVE_SET: ucc_coll_args_field = 16;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_MEM_MAP_SRC_MEMH: ucc_coll_args_field = 32;
pub const ucc_coll_args_field_UCC_COLL_ARGS_FIELD_MEM_MAP_DST_MEMH: ucc_coll_args_field = 64;
#[doc = "  @ingroup UCC_COLLECTIVES_DT"]
pub type ucc_coll_args_field = ::std::os::raw::c_uint;
pub type ucc_mem_map_mem_h = *mut ::std::os::raw::c_void;
#[doc = "  @ingroup UCC_COLLECTIVES\n\n  @brief Structure representing arguments for the collective operations\n\n  @parblock\n\n  @b Description\n  @n @n\n  @ref ucc_coll_args_t defines the parameters that can be used to customize\n  the collective operation. The \"mask\" bit array fields are defined by @ref\n  ucc_coll_args_field. The bits in \"mask\" bit array is defined by @ref\n  ucc_coll_args_field, which correspond to fields in structure @ref\n  ucc_coll_args_t. The valid fields of the structure are specified by\n  setting the corresponding bit to \"1\" in the bit-array \"mask\".\n  @n @n\n  The collective operation is selected by field \"coll_type\" which must be always\n  set by user. If allreduce or *  reduce operation is selected, the type of\n  reduction is selected by the field *  \"predefined_reduction_op\" or\n  \"custom_reduction_op\". For unordered collective\n  operations, the user-provided \"tag\" value orders the collective operation.\n  For rooted collective operations such as reduce, scatter, gather, fan-in, and\n  fan-out, the \"root\" field  must be provided by user and specify the participant\n  endpoint value. The user\n  can request either \"local\" or \"global\" error information using the\n  \"error_type\" field.\n\n  @n @n\n  Information about user buffers used for collective operation must be specified\n  according to the \"coll_type\".\n  @endparblock\n"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ucc_coll_args {
    pub mask: u64,
    #[doc = "< Type of collective operation"]
    pub coll_type: ucc_coll_type_t,
    pub src: ucc_coll_args__bindgen_ty_1,
    pub dst: ucc_coll_args__bindgen_ty_2,
    #[doc = "< Predefined reduction operation, if\nreduce, allreduce, reduce_scatter\noperation is selected.\nThe field is only specified for collectives\nthat use pre-defined datatypes"]
    pub op: ucc_reduction_op_t,
    #[doc = "< Provide flags and hints for the\ncollective operations"]
    pub flags: u64,
    #[doc = "< Root endpoint for rooted\ncollectives"]
    pub root: u64,
    #[doc = "< Error type"]
    pub error_type: ucc_error_type_t,
    #[doc = "< Used for ordering collectives"]
    pub tag: ucc_coll_id_t,
    #[doc = "< User allocated scratchpad\nbuffer for one-sided\ncollectives. The buffer\nprovided should be at least\nthe size returned by @ref\nucc_context_get_attr with\nthe field mask -\nUCC_CONTEXT_ATTR_FIELD_WORK_BUFFER_SIZE\nset to 1. The buffer must be initialized\nto 0."]
    pub global_work_buffer: *mut ::std::os::raw::c_void,
    pub cb: ucc_coll_callback_t,
    #[doc = "< Timeout in seconds"]
    pub timeout: f64,
    pub active_set: ucc_coll_args__bindgen_ty_3,
    pub src_memh: ucc_coll_args__bindgen_ty_4,
    pub dst_memh: ucc_coll_args__bindgen_ty_5,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucc_coll_args__bindgen_ty_1 {
    #[doc = "< Buffer info for the collective"]
    pub info: ucc_coll_buffer_info_t,
    #[doc = "< Buffer info for the collective"]
    pub info_v: ucc_coll_buffer_info_v_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucc_coll_args__bindgen_ty_2 {
    #[doc = "< Buffer info for the collective"]
    pub info: ucc_coll_buffer_info_t,
    #[doc = "< Buffer info for the collective"]
    pub info_v: ucc_coll_buffer_info_v_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_coll_args__bindgen_ty_3 {
    pub start: u64,
    pub stride: i64,
    pub size: u64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucc_coll_args__bindgen_ty_4 {
    #[doc = "< Memory handle of locally\nmapped memory for the src\nbuffer"]
    pub local_memh: ucc_mem_map_mem_h,
    #[doc = "< Array of memory handles\nfor the src buffer\ncorresponding to all\nparticipating processes\nin the collective"]
    pub global_memh: *mut ucc_mem_map_mem_h,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ucc_coll_args__bindgen_ty_5 {
    #[doc = "< Memory handle of locally\nmapped memory for the dst\nbuffer"]
    pub local_memh: ucc_mem_map_mem_h,
    #[doc = "< Array of memory handles\nfor the dst buffer\ncorresponding to all\nparticipating processes\nin the collective"]
    pub global_memh: *mut ucc_mem_map_mem_h,
}
#[doc = "  @ingroup UCC_COLLECTIVES\n\n  @brief Structure representing arguments for the collective operations\n\n  @parblock\n\n  @b Description\n  @n @n\n  @ref ucc_coll_args_t defines the parameters that can be used to customize\n  the collective operation. The \"mask\" bit array fields are defined by @ref\n  ucc_coll_args_field. The bits in \"mask\" bit array is defined by @ref\n  ucc_coll_args_field, which correspond to fields in structure @ref\n  ucc_coll_args_t. The valid fields of the structure are specified by\n  setting the corresponding bit to \"1\" in the bit-array \"mask\".\n  @n @n\n  The collective operation is selected by field \"coll_type\" which must be always\n  set by user. If allreduce or *  reduce operation is selected, the type of\n  reduction is selected by the field *  \"predefined_reduction_op\" or\n  \"custom_reduction_op\". For unordered collective\n  operations, the user-provided \"tag\" value orders the collective operation.\n  For rooted collective operations such as reduce, scatter, gather, fan-in, and\n  fan-out, the \"root\" field  must be provided by user and specify the participant\n  endpoint value. The user\n  can request either \"local\" or \"global\" error information using the\n  \"error_type\" field.\n\n  @n @n\n  Information about user buffers used for collective operation must be specified\n  according to the \"coll_type\".\n  @endparblock\n"]
pub type ucc_coll_args_t = ucc_coll_args;
extern "C" {
    #[doc = "  @ingroup UCC_COLLECTIVES\n\n  @brief The routine to initialize a collective operation.\n\n  @param [in]    coll_args   Collective arguments descriptor\n  @param [out]   request     Request handle representing the collective operation\n  @param [in]    team        Team handle\n\n  @parblock\n\n  @b Description\n\n  @ref  ucc_collective_init is a collective initialization operation,\n  where all participants participate. The user provides all information\n  required to start and complete the collective operation, which includes the\n  input and output buffers, operation type, team handle, size, and any other\n  hints for optimization. On success, the request handle is created and\n  returned. On error, the request handle is not created and the appropriate\n  error code is returned. On return, the ownership of buffers is transferred\n  to the user. If modified, the results of collective operations posted on the\n  request handle are undefined.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_collective_init(
        coll_args: *mut ucc_coll_args_t,
        request: *mut ucc_coll_req_h,
        team: ucc_team_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_COLLECTIVES\n\n  @brief The routine to post a collective operation.\n\n  @param [in]     request     Request handle\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_collective_post routine posts the collective operation. It\n  does not require synchronization between the participants for the post\n  operation. On error, request handle becomes invalid, user is responsible\n  to call ucc_collective_finalize to free allocated resources.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_collective_post(request: ucc_coll_req_h) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_COLLECTIVES\n\n  @brief The routine to initialize and post a collective operation.\n\n  @param [out]     request     Request handle representing the collective operation\n  @param [in]      coll_args   Collective arguments descriptor\n  @param [in]      team        Input Team\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_collective_init_and_post initializes the collective operation\n  and also posts the operation.\n\n  @note: The @ref ucc_collective_init_and_post can be implemented as a\n  combination of @ref ucc_collective_init and @ref ucc_collective_post\n  routines.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_collective_init_and_post(
        coll_args: *mut ucc_coll_args_t,
        request: *mut ucc_coll_req_h,
        team: ucc_team_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = "  @ingroup UCC_COLLECTIVES\n\n  @brief The routine to release the collective operation associated with the request object.\n\n  @param [in] request - Request handle\n\n  @parblock\n\n  @b Description\n\n  @ref ucc_collective_finalize operation releases all resources\n  associated with the collective operation represented by the request handle.\n  In UCC_THREAD_MULTIPLE mode, the user is responsible for ensuring that\n  @ref ucc_collective_finalize is called after the status is UCC_OK and after\n  completing the execution of any callback registered with @ref ucc_coll_args_t.\n\n  @endparblock\n\n  @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_collective_finalize(request: ucc_coll_req_h) -> ucc_status_t;
}
pub const ucc_event_type_UCC_EVENT_COLLECTIVE_POST: ucc_event_type = 1;
pub const ucc_event_type_UCC_EVENT_COLLECTIVE_COMPLETE: ucc_event_type = 2;
pub const ucc_event_type_UCC_EVENT_COMPUTE_COMPLETE: ucc_event_type = 4;
pub const ucc_event_type_UCC_EVENT_OVERFLOW: ucc_event_type = 8;
#[doc = " @ingroup UCC_EVENT_DT\n"]
pub type ucc_event_type = ::std::os::raw::c_uint;
#[doc = " @ingroup UCC_EVENT_DT\n"]
pub use self::ucc_event_type as ucc_event_type_t;
pub const ucc_ee_type_UCC_EE_FIRST: ucc_ee_type = 0;
pub const ucc_ee_type_UCC_EE_CUDA_STREAM: ucc_ee_type = 0;
pub const ucc_ee_type_UCC_EE_CPU_THREAD: ucc_ee_type = 1;
pub const ucc_ee_type_UCC_EE_ROCM_STREAM: ucc_ee_type = 2;
pub const ucc_ee_type_UCC_EE_LAST: ucc_ee_type = 3;
pub const ucc_ee_type_UCC_EE_UNKNOWN: ucc_ee_type = 3;
#[doc = " @ingroup UCC_EVENT_DT\n"]
pub type ucc_ee_type = ::std::os::raw::c_uint;
#[doc = " @ingroup UCC_EVENT_DT\n"]
pub use self::ucc_ee_type as ucc_ee_type_t;
#[doc = " @ingroup UCC_EVENT_DT\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_event {
    pub ev_type: ucc_event_type_t,
    pub ev_context: *mut ::std::os::raw::c_void,
    pub ev_context_size: usize,
    pub req: ucc_coll_req_h,
}
#[doc = " @ingroup UCC_EVENT_DT\n"]
pub type ucc_ev_t = ucc_event;
#[doc = " @ingroup UCC_EVENT_DT\n"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ucc_ee_params {
    pub ee_type: ucc_ee_type_t,
    pub ee_context: *mut ::std::os::raw::c_void,
    pub ee_context_size: usize,
}
#[doc = " @ingroup UCC_EVENT_DT\n"]
pub type ucc_ee_params_t = ucc_ee_params;
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine creates the execution context for collective operations.\n\n @param [in]  team    Team handle\n @param [in]  params  User provided params to customize the execution engine\n @param [out] ee      Execution engine handle\n\n @parblock\n\n @b Description\n\n @ref ucc_ee_create creates the execution engine. It enables event-driven\n collective execution. @ref ucc_ee_params_t allows the execution engine to be\n configured to abstract either GPU and CPU threads. The execution engine is\n created and coupled with the team. There can be many execution engines\n coupled to the team. However, attaching the same execution engine to multiple\n teams is not allowed. The execution engine is created after the team is\n created and destroyed before the team is destroyed. It is the user's\n responsibility to destroy the execution engines before the team. If the team\n is destroyed before the execution engine is destroyed, the result is\n undefined.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_ee_create(
        team: ucc_team_h,
        params: *const ucc_ee_params_t,
        ee: *mut ucc_ee_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine destroys the execution context created for collective operations.\n\n @param [in] ee   Execution engine handle\n\n @parblock\n\n @b Description\n\n @ref ucc_ee_destroy releases the resources attached with the\n execution engine and destroys the execution engine. All events and triggered\n operations related to this ee are invalid after the destroy operation. To\n avoid race between the creation and destroying the execution engine, for a\n given ee, the @ref ucc_ee_create and @ref ucc_ee_destroy must be invoked from\n the same thread.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_ee_destroy(ee: ucc_ee_h) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine gets the event from the event queue.\n\n @param [in]  ee        Execution engine handle\n @param [out] ev        Event structure fetched from the event queue\n\n @parblock\n\n @b Description\n\n @ref ucc_ee_get_event fetches the events from the execution engine. If there\n are no events posted on the ee, it returns immediately without waiting for\n events. All events must be acknowledged using the @ref ucc_ee_ack_event\n interface. The event acknowledged is destroyed by the library. An event\n fetched with @ref ucc_ee_get_event but not acknowledged might consume\n resources in the library.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_ee_get_event(ee: ucc_ee_h, ev: *mut *mut ucc_ev_t) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine acks the events from the event queue.\n\n @param [in]  ee      Execution engine handle\n @param [in]  ev      Event to be acked\n\n @parblock\n\n @b Description\n\n An event acknowledged by the user using @ref ucc_ee_ack_event is destroyed by\n the library. Any triggered operations on the event should be completed before\n calling this interface. The behavior is undefined if the user acknowledges\n the event while waiting on the event or triggering operations on the event.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_ee_ack_event(ee: ucc_ee_h, ev: *mut ucc_ev_t) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine to set the event to the tail of the queue.\n\n @param [in]  ee        Execution engine handle\n @param [in]  ev        Event structure fetched from the event queue\n\n @parblock\n\n @b Description\n\n @ref ucc_ee_set_event sets the event on the execution engine. If the\n operations are waiting on the event when the user sets the event, the\n operations are launched. The events created by the user need to be destroyed\n by the user.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_ee_set_event(ee: ucc_ee_h, ev: *mut ucc_ev_t) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine blocks the calling thread until there is an event on the queue.\n\n @param [in]  ee        Execution engine handle\n @param [out] ev        Event structure fetched from the event queue\n\n @parblock\n\n @b Description\n\n The user thread invoking the @ref ucc_ee_wait interface is blocked until an\n event is posted to the execution engine.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_ee_wait(ee: ucc_ee_h, ev: *mut ucc_ev_t) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_EVENT\n\n @brief The routine posts the collective operation on the execution engine, which is\n launched on the event.\n\n @param [in]  ee          Execution engine handle\n @param [in]  ee_event    Event triggering the post operation\n\n @parblock\n\n @b Description\n\n @ref ucc_collective_triggered_post allow the users to schedule a collective\n operation that executes in the future when an event occurs on the execution\n engine. On error, request handle associated with event becomes invalid,\n user is responsible to call ucc_collective_finalize to free allocated resources.\n\n @endparblock\n\n @return Error code as defined by @ref ucc_status_t"]
    pub fn ucc_collective_triggered_post(ee: ucc_ee_h, ee_event: *mut ucc_ev_t) -> ucc_status_t;
}
#[doc = "< Indicate ucc_mem_map() should export\nmemory handles from TLs used by\ncontext"]
pub const ucc_mem_map_mode_t_UCC_MEM_MAP_MODE_EXPORT: ucc_mem_map_mode_t = 0;
#[doc = "< Indicate ucc_mem_map() should import\nmemory handles from user memory handle"]
pub const ucc_mem_map_mode_t_UCC_MEM_MAP_MODE_IMPORT: ucc_mem_map_mode_t = 1;
#[doc = "< Indicate ucc_mem_map() should\nexport memory handles from TLs used\nby a context on an offloaded\ndevice"]
pub const ucc_mem_map_mode_t_UCC_MEM_MAP_MODE_EXPORT_OFFLOAD: ucc_mem_map_mode_t = 2;
#[doc = "< Indicate ucc_mem_map() should import\nmemory handles from a host's memory\nhandle to an offloaded device"]
pub const ucc_mem_map_mode_t_UCC_MEM_MAP_MODE_IMPORT_OFFLOAD: ucc_mem_map_mode_t = 3;
pub const ucc_mem_map_mode_t_UCC_MEM_MAP_MODE_LAST: ucc_mem_map_mode_t = 4;
#[doc = " @ingroup UCC_DATATYPE"]
pub type ucc_mem_map_mode_t = ::std::os::raw::c_uint;
extern "C" {
    #[doc = " @ingroup UCC_CONTEXT\n @brief Routine registers or maps memory for use in future collectives.\n\n This local routine maps a user-specified memory segment with a\n ucc_context_h. The segment is considered \"mapped\" with the context until\n the user calls ucc_mem_unmap. It is the user's responsibility to unmap all\n mapped segments prior to calling ucc_context_destroy(). A handle to the\n mapped memory is provided in memh. If the mode UCC_MEM_MAP_MODE_EXPORT is used,\n the memory will be mapped and memory handles from TLs will be generated and\n stored in the memh. If the mode UCC_MEM_MAP_MODE_IMPORT is used, the user must\n provide a valid memh, otherwise behavior is undefined.\n\n @param [in] context     Context mapped memory is associated with\n @param [in] mode        mode dictating the behavior of the routine\n @param [in] params      parameters indicating the address and length of\n                          memory to map\n @param [out] memh_size  Size of memory handle when exported\n @param [inout] *memh    Handle for the registered memory\n\n @return Error code as defined by ucc_status_t."]
    pub fn ucc_mem_map(
        context: ucc_context_h,
        mode: ucc_mem_map_mode_t,
        params: *const ucc_mem_map_params_t,
        memh_size: *mut usize,
        memh: *mut ucc_mem_map_mem_h,
    ) -> ucc_status_t;
}
extern "C" {
    #[doc = " @ingroup UCC_CONTEXT\n @brief Routine unmaps memory from a context\n\n This is a local routine that unmaps memory and all resources\n associated with the memory from a context. The memh object is freed and\n cannot be reused.\n\n @param [in] *memh       Handle of the registered memory\n\n @return Error code as defined by ucc_status_t."]
    pub fn ucc_mem_unmap(memh: *mut ucc_mem_map_mem_h) -> ucc_status_t;
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
